### ISSUE TITLE
Exponential backoff

### ISSUE THREAD

**Issue by shoyer** [d0ugal/retrace#1]
This is the critical feature I want for a retrying library.

**Comment by d0ugal** [comment]
This would be trivial to implement. Can you give more specifics about exactly you want and what you would need to be able to configure?

**Comment by shoyer** [comment]
Sure. In my typical use I want to wrap a specific error (e.g., `IOError`) that is raised when I hit a remote server too hard. Exponential backoff is a good strategy for this. Adding some randomness is also a good strategy to avoid synchronized errors in the case of concurrent requests.

Here's the little helper function I wrote for doing this. As you can see, the configurable parameters are the exception types to catch, the maximum number of retries and the initial delay.
https://github.com/xray/xray/blob/v0.5.2/xray/backends/common.py#L50-L72

**Comment by d0ugal** [comment]
This has actually been possible for some time, however I finally got around to adding an example to the docs. A few custom lines of code is needed, but as it is so simple I don't think we need to add specific support for it at the moment.
