### ISSUE TITLE
Raise original exception instead of LimitReached

### ISSUE THREAD

**Issue by berislavlopac** [d0ugal/retrace#4]
It might be a good idea to raise the original exception when the limit is reached so it can be handled by surrounding code (as it means that the retrying failed). Alternatively, if needed to preserve compatibility, the original exception could be an attribute on the `LimitReached` exception so it can easily be accessed.

Thoughts?

**Comment by d0ugal** [comment]
Interesting, yes, I think that would have been a better idea.

For now, let's add it as an attribute and we can look at changing the behaviour in the future when we make the next major release.

**Comment by andreyrusanov** [comment]
@d0ugal @berislavlopac  I also like this idea. Could you assign an issue to me and I will make a PR today's evening or tomorrow morning?

**Comment by berislavlopac** [comment]
Thanks @andreyrusanov! Sorry guys, I've been planning to implement that for a while but have been insanely busy lately so kept postponing it. :disappointed:

**Comment by d0ugal** [comment]
I actually spent some time looking into this, but got a bit stuck - I don't think it is as trivial as it looks. However, @andreyrusanov, please go ahead and give it a try. I think you can just use this issue.

**Comment by andreyrusanov** [comment]
Guys, I've opened the PR. The idea is to keep `reasons_list` which will hold all the exceptions happened. Afterwards this list copied to `exceptions_list`, an attributed in LimitReached exception.
If you are OK with the approach and realization please let me know - I will update tests and docs as well.

**Comment by d0ugal** [comment]
I think it looks good from a glance. I need to find some time to try it out and have a play. Hopefully I can do that tomorrow.

**Comment by andreyrusanov** [comment]
@d0ugal the only thing there that I missed is the case when somebody will try to add custom class as a limit an will not inherit it from `ReasonsMixin`. Some error should be raised, in this case, perhaps.
